AerolineaBundle\Entity\Pasajero:
    type: entity
    table: Pasajero
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        genero:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: Genero
    manyToMany:
        vuelo:
            targetEntity: Vuelo
            cascade: {  }
            fetch: LAZY
            mappedBy: pasajero
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
