# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    locale: nl
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.security.access_denied_handler:
        class: AerolineaBundle\Security\AccessDeniedHandler
